### ISSUE TITLE
1007 invalid payload size for control frame

### ISSUE THREAD

**Issue by akaabe** [tidwall/SwiftWebSocket#31] opened 2016-02-05 16:54 UTC
Getting such error on communication with server. Seems related to network issues (response form server is > 200msec). Connection is established but data from server is not returned via web socket. Wrong frame begins with byte 0x81

**Comment by dru** [comment] 2016-02-05 17:42
According to this reference http://www.tbray.org/drafts/wsock-00

"4.2.1.  Input Data Framing
...
 Thus, a frame beginning with 0x81 0x82 0x83 0x04 has a length of (1 \* 128 \* 128) + (2 \* 128) + 3, or 16643. The frame length applies only to the data which follows the encoding of the length.

Clients MUST read and ignore frames which begin with a length, and only process those which begin with 0x00.
...
"
but in code looks like exception is thrown
https://github.com/tidwall/SwiftWebSocket/blob/master/Source/WebSocket.swift#L260

**Comment by tidwall** [comment] 2016-02-05 20:47
@akaabe That error indicates that the control frames payload size is out of range. 
A control frame cannot have a payload larger than 125 bytes in length as stated in RFC 6455

```
5.5.  Control Frames
   ...
   All control frames MUST have a payload length of 125 bytes or less
   and MUST NOT be fragmented.
```

Do you think that that might be the culprit?

**Comment by tidwall** [comment] 2016-02-05 20:50
@akaabe Do you happen to have the frame in it's entirety for investigation?

**Comment by akaabe** [comment] 2016-02-08 12:02
Please use dump of network. 
https://www.dropbox.com/s/i9kv18pczpcwxia/dump.pcapng?dl=0
To open dump use wireshark. iOS is on .22 ip address

**Comment by tidwall** [comment] 2016-04-13 15:26
I'm closing this issue for now.  We are not able to reproduce. Please feel free to reopen if needed. Thanks.

**Closed as completed by tidwall** 2016-04-13 15:26 UTC
