### ISSUE TITLE
Crash when resuming app from background

### ISSUE THREAD

**Issue by netgfx** [tidwall/SwiftWebSocket#44] opened 2016-05-19 07:30 UTC
Hello I have a crash each time the user is on a socket related view and the App is on the background for a long time. When the App resumes it crashes.
Any idea what causes this? I'm using Python for Backend with wss protocol.

```
libsystem_kernel​.dylib   
__psynch_cvwait
1   WebSocket.swift ​Line ​1616
(Manager in _A42D883B1EA5865CEB62599B0B6EDEEA).(init() -> (Manager in _A42D883B1EA5865CEB62599B0B6EDEEA)).(closure #1)

        let v1 = Int(tv.tv_usec * 1000)
        let v2 = Int(1000 * 1000 * Int(timeInMs % 1000))
        ts.tv_nsec = v1 + v2;
        ts.tv_sec += ts.tv_nsec / (1000 * 1000 * 1000);
        ts.tv_nsec %= (1000 * 1000 * 1000);
        return pthread_cond_timedwait(&self.cond, &self.mutex, &ts)
    }
    func signal(){
        pthread_mutex_lock(&mutex)
        pthread_cond_signal(&cond)
        pthread_mutex_unlock(&mutex)

2   libdispatch​.dylib    
_dispatch_call_block_and_release
3   libdispatch​.dylib    
_dispatch_client_callout
4   libdispatch​.dylib    
_dispatch_queue_drain
5   libdispatch​.dylib    
_dispatch_queue_invoke
6   libdispatch​.dylib    
_dispatch_client_callout
7   libdispatch​.dylib    
_dispatch_root_queue_drain
8   libdispatch​.dylib    
_dispatch_worker_thread3
9   libsystem_pthread​.dylib  
_pthread_wqthread
10  libsystem_pthread​.dylib  
start_wqthread
```

**Comment by tidwall** [comment] 2016-05-19 17:30
Thanks for reporting this @netgfx. I haven't encountered this issue before now. I would like to reproduce it. Does this crash happen in the simulator, on the device, or both? Are you running Xcode 7.3.1?

**Comment by netgfx** [comment] 2016-05-20 08:05
Yes using xcode 7.3.1 and iOS device (only happens on device) 9.3.2/9.3.1 
Over wifi or cellular. Socket is open and receiving messages from python but App is on background.
The inactivity must be over 15' - 20'
The line reported by the debugger is this:
`return pthread_cond_timedwait(&self.cond, &self.mutex, &ts)`

**Comment by tidwall** [comment] 2016-05-20 13:37
I haven't been able to reproduce this crash yet. 

What I've tried was I created a simple app that loads a websocket from viewDidLoad, and receives small messages (around 50 bytes) 5 times a second and print these messages to the Xcode console. 

After about 10 seconds I send the app to the background by pressing the Home button. The app receives few more messages (around 5) and prints these to the console. After a few minutes my iphone goes to sleep. I wait about 30 minutes then I awaken the device and bring the app to the foreground. The websocket immediately receives the event `Network(The operation couldn’t be completed. Socket is not connected)`. But there isn't a crash.

**Comment by netgfx** [comment] 2016-05-20 14:43
Interesting, the thing is this crash doesn't appear consistently but it appears. So I don't have an exact reproduction route. In my app I have a socket that opens on a wss:// protocol server, and subscribes to  a thread (room). Then the app goes to the background and after X-amount of time it is brought back to foreground and then it sometimes crashes. 
I have to add that I have never experienced this when the device is connected to the Mac OS via cable. It only happened when the device is not connected via cable.

**Comment by tidwall** [comment] 2016-05-20 16:08
That's helpful info. Couple more questions if you don't mind. Are you creating the websocket from the UI thread? Does this happen in debug or release? And do you have any background modes set in the Info.plist file?

**Comment by netgfx** [comment] 2016-05-20 16:15
- The socket creation is indeed created on the main thread.
- This is happening mostly on release
- Not sure what background modes are, so I presume I don't have anything declared there.

**Comment by tidwall** [comment] 2016-08-24 13:13
Hi Michael.

 I'm sorry for responding after so long. 

I'm going to close the issue for now because there's been a few updates to the project since this issue has first opened.  But if this is still a problem please feel free to reopen the issue or create a new one. 

Thanks for supporting the project.

**Closed as completed by tidwall** 2016-08-24 13:13 UTC
