### ISSUE TITLE
Getting streamStatus.atEnd when connecting to web socket server under SSL

### ISSUE THREAD

**Issue by WolneyEEG** [tidwall/SwiftWebSocket#34] opened 2016-03-02 23:26 UTC
Hello,

I have created the NodeJs project to host a server:

`
var fs = require('fs');
var https = require('https');

var express = require('express');
var app = express();

// Preparing for HTTPS hosting (This is not a self signed certificate and it is green on chrome)
var sslDir = '/home/wolney/Applications/ssl/'
var privateKey = fs.readFileSync(sslDir+'server.key');
var certificate = fs.readFileSync(sslDir+'server.crt');
var certificateAuthority = fs.readFileSync(sslDir+'sub.class1.server.ca.pem');

var credentials = {key: privateKey, cert: certificate, ca: certificateAuthority};

var serverPort = 443;

var server = https.createServer(credentials, app);
var io = require('socket.io')(server);

app.get('/', function(req, res) {
  res.sendFile(__dirname + '/public/index.html');
});

io.on('connection', function(socket) {
  console.log('new connection');
  socket.emit('message', 'This is a message from the dark side.');
});

server.listen(serverPort, function() {
  console.log('server up and running at %s port', serverPort);
});
`
public/index.html is:

`
<!doctype html>
<html>
  <head>
  </head>
  <body>
    <h1>I am alive!!</h1>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.js"></script>
    <script>
      var URL_SERVER = 'https://apex5associates.com:443';
      var socket = io.connect(URL_SERVER);
      socket.on('message', function(data) {
        alert(data);
      });
    </script>
  </body>
</html>
`

It woks fine when using the browser in the browser.

However when I try to access via my app running in the simulator I get error event with <B>Network(streamStatus.atEnd)</B>. The code I am using was copied from the sample:

`
func echoTest(){
        let request = NSMutableURLRequest(URL: NSURL(string:"wss://apex5associates.com:443")!)
        let ws = WebSocket(request: request)

```
    var messageNum = 0
    let send : ()->() = {
        let msg = "\(++messageNum): \(NSDate().description)"
        print("send: \(msg)")
        ws.send(msg)
    }
    ws.event.open = {
        print("opened")
        send()
    }
    ws.event.close = { code, reason, clean in
        print("close")
    }
    ws.event.error = { error in
        print("error \(error)")
    }
    ws.event.message = { message in
        if let text = message as? String {
            print("recv: \(text)")
            if messageNum == 10 {
                ws.close()
            } else {
                send()
            }
        }
    }
}
```

`

Any idea on what I doing wrong?

Thanks in advance

**Comment by tidwall** [comment] 2016-03-02 23:51
Hi,  I just tried to connect and the server immediately hung up. I tested using a console app called [wscat](https://www.npmjs.com/package/wscat) `wscat -c wss://apex5associates.com:443`. 

I notice that your javascript example uses socket.io. I'm not familiar with socket.io, but perhaps the problem might have to do with the server expecting a different handshake or protocol than what standard websocket provides? Do you have a Javascript example that uses a WebSocket connection instead of socket.io?

**Comment by tidwall** [comment] 2016-03-24 12:34
@WolneyEEG, I'm closing this issue because I need an reproducible example using only websockets. Feel free to reopen if you are still running into a problem and have more details. Thanks!

**Closed as completed by tidwall** 2016-03-24 12:34 UTC
