### ISSUE TITLE
sluggish performance after reconnecting for a couple of times

### ISSUE THREAD

**Issue by mohsenShakiba** [tidwall/SwiftWebSocket#24] opened 2016-01-18 07:36 UTC
I have a ViewController in which I'm using the WebSocket.
there is also a UITableView in myViewController.
I only initialize the WebSocket once, and then close and open if needed.
but every time I close the WebSocket, and open it again(without re creating any object) the tableView gets more sluggish. as if after 5 times it gets really slow.
the cpu doesn't show anything and ram usage is normal.
but still everything is super slow, even the OS it self
I'm using ipad mini2 and iOS 9.3
any guess what this could be?

**Comment by tidwall** [comment] 2016-01-18 14:59
What do you mean by sluggish? Is tableview scrolling slow, or the entire app? I would like to reproduce this issue. Could you provide the steps to recreate this problem?

If I were to guess then I would say that it has to do with some type of blocking occurring when the main runloop is in UITrackingRunLoopMode.

**Comment by mohsenShakiba** [comment] 2016-01-18 15:57
yes, the tableview becomes slow, any other tableviews that I add afterwards, by using the addSubVIew and addChildController still work smooth but the tableView inside the main UIViewController is really slow.
to reproduce the issue, I would suggest to just create a normal tableView with limited rows(mine had 5) and the have the websocket initialized inside the UIViewController that is also the datasource and the delegate for the tableView. then have the socket closed and opened several time(as much as it gets sluggish, for me it took 4-5 times) and it should to the trick.
like I said, I had the websocket initialized in my UIViewController which also was the dataSource and the delegate for table view.
if you close and open the websocket several times, the tableView will be really slow when dragging.
thanks for your time :-)

**Comment by tidwall** [comment] 2016-01-18 23:40
I'm not able to reproduce the issue. I created a new app with a `UIViewController`. I added a `UITableView` and set the delegate and dataSource to the `UIViewController`. I then displayed 1,000 table cells and set the textLabel to 1...1000.  I then started a websocket (I used the echo service in the README). Finally I set the `ws.open(); ws.close()` actions to the `didSelectRowAtIndexPath`.

I was able to close and reopen dozens of connections without seeing any sluggishness. 

Could you create a simple test project that presents this issue and attach it to this thread? 

Thanks a ton.

**Comment by mohsenShakiba** [comment] 2016-01-19 07:15
sure I'll create a sample project
and try to see at what point, and after what action exactly the table view goes sluggish
I'll post the results ASAP
thanks

**Comment by tidwall** [comment] 2016-02-02 22:54
I'm closing this issue because it's not reproducible.

**Closed as completed by tidwall** 2016-02-02 22:54 UTC
